### ISSUE TITLE
Changelog deprecation

### ISSUE THREAD

**Issue by julienmartinlevrai** [nanexcool/daistats#118]
Hello,

From May 1st. 2022 onwards, `changelog.makerdao.com` will stop receiving updates. Please use [chainlog.makerdao.com](https://chainlog.makerdao.com).

Thank you

**Comment by devenoges** [comment]
Hi Julien,

thanks for the heads up. resolved in 1343ef1592891a5d0ef0b564d239bb3d5b51554a
