### ISSUE TITLE
Add "deprecated" subsection to collateral tab

### ISSUE THREAD

**Issue by monet-supply** [nanexcool/daistats#122]
I think it could improve UX to move all of the fully offboarded ERC-20 vault types (those with both 0 maximum debt ceiling [line] and 0 outstanding debt) to a separate "deprecated" tab.

Currently, the following assets would qualify as deprecated: BAT-A, USDC-B, TUSD-A, KNC-A, ZRX-A, USDT-A, COMP-A, LRC-A, BAL-A, AAVE-A, UNIV2LINKETH-A, and UNIV2AAVEETH-A

This would reduce the number of assets in the ERC-20 list by more than a quarter, making it easier to navigate.

**Comment by devenoges** [comment]
Thanks for the suggestion.
