### ISSUE TITLE
Extra Metrics

### ISSUE THREAD

**Issue by devenoges** [nanexcool/daistats#49]
- show next possible OSM price change time
- under SCD MKR price, show uniswap MKR/ETH price
- under Dai in Uniswap, show Mkr in Uniswap
- show time of last Eth & Bat flip liquidation, also flap and flop

**Comment by ddaws** [comment]
I created a ticket here for "under Dai in Uniswap, show Mkr in Uniswap" so I can take this change on individually as my first PR to daistats

**Comment by ddaws** [comment]
Created a ticket for "under SCD MKR price, show uniswap MKR/ETH price" so I can this one :)
