### ISSUE TITLE
One row per collateral

### ISSUE THREAD

**Issue by zdumitru** [nanexcool/daistats#70]
There are 8 different collaterals now. And more are on the way. With that many collateral types it is difficult to have an overview of what is where. I was thinking to have one row per collatteral that would look something like that:

|||||||
|-|-|-|-|-|-|
|Dai generated from ETH|ETH Ceiling (in Dai)|ETH Stability Fee|ETH Locked (in ETH)|ETH Price|ETH Address|
|Dai generated from BAT|BAT Ceiling (in Dai)|BAT Stability Fee|BAT Locked (in BAT)|BAT Price|BAT Address|
|Dai generated from WBTC|WBTC Ceiling (in Dai)|WBTC Stability Fee|WBTC Locked (in WBTC)|WBTC Price|WBTC Address|
|etc...||||||

And when a new collateral is added, it will be a new row added to the table that would have the same format.

If that is fine, I can also make a PR to bring it to that format.

**Comment by nanexcool** [comment]
@zdumitru I'm in the middle of a redesign, but if you can submit a PR for these rows, it would be great!
