### ISSUE TITLE
Not an issue , just need some info.

### ISSUE THREAD

**Issue by harsh-98** [nanexcool/daistats#76]
What are flip auctions shown on daistats? 
How is chai supply shown calculated? 
Also for usdt 378M/400M is shown and locked USDT is 385M. So how do you get 400M, as the max dai that usdt can back?

**Comment by devenoges** [comment]
- Flip auctions are under collateralized valuts that are sold off to bring them back below the required ratio for the respective collateral type. 
 - Chai supply is `totalSupply` for the erc-20 contract.
 - The 400M would have been the Debt Ceiling for USDT at that time.
