### ISSUE TITLE
UI showing incorrect amount of GUSD locked in GUSD join adapter

### ISSUE THREAD

**Issue by Lollike** [nanexcool/daistats#83]
The UI is showing that 0 GUSD is locked in the GUSD-A join adapter, [when there is is in fact 700 locked](https://etherscan.io/address/0xe29A14bcDeA40d83675aa43B72dF07f649738C8b).
I tried updating the gusdALocked in App.jsx from:
`const gusdALocked = pax.interface.decodeFunctionResult('balanceOf', res[127])`

To:
`const gusdALocked = gusd.interface.decodeFunctionResult('balanceOf', res[127])`

But that did not seem to fix the issue.

**Comment by devenoges** [comment]
Issue was GUSD has 2 decimals, resolved in pr #85
